# Generated by Django 5.2 on 2025-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400)),
                ('content', models.TextField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('REAL', 'REAL'), ('FAKE', 'FAKE')], default='REAL', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
