# Generated by Django 5.2 on 2025-06-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_detection', '0002_alter_newsarticle_options_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='article',
        ),
    ]
